name: test-runner

on: [push]

jobs:
  deploy:
    runs-on: self-hosted #ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Current Directory
      run: pwd

    - name: Check running docker services
      run: sudo docker ps

    - name: Stop Docker Container
      run: sudo docker stop csn-nginx || true

    - name: Delete the Docker Container
      run: sudo docker rm csn-nginx || true

    - name: Build Nginx Docker Image
      run: sudo docker build -t csn-nginx .

    - name: Run the Docker Container
        run: sudo docker run -it --rm -d -p 80:80 --name csn-nginx csn-nginx
    
    - name: Test the web service
      run: curl http://localhost:8080
