name: test-runner

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Current Directory
      run: pwd

    - name: checkout running docker services
      run: sudo docker ps
    
    - name: Build Nginx Docker Image 
      run: sudo docker build -t csn-nginx .

    - name: Stop Docker Container
      run: sudo docker stop csn-nginx || true

    - name: Delete the Docker Container
      run: sudo docker rm csn-nginx || true

    - name: Run the Docker Container
      run: sudo docker run -d --name csn-nginx -p 8080:80 csn-nginx

    - name: Test the web service
      run: curl http://localhost:8080
